apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpmt-api
    namespace: "default"
spec:
    selector:
        matchLabels:
            app: gpmt-api
    template:
        metadata:
            labels:
                app: gpmt-api
        spec:
            containers:
            - name: gpmt-api
              image: gpmtcontainerregistry.azurecr.io/gpmt-api:latest
              imagePullPolicy: Always
              env:
              - name: AUTH_SIGN_SECRET 
                value: "abc"
              - name: HASH_SALT_ROUNDS
                value: "10"
              - name: PORT
                value: "80"
              - name: STORAGE_CONNECTION_URL
                valueFrom:
                  secretKeyRef:
                    name: azure-storage
                    key: url
              - name: MONGO_URL
                valueFrom:
                  secretKeyRef:
                    name: cosmosdb
                    key: url
              - name: RASA_URL
                value: "http://rasa-x-rasa-production.rasa.svc.cluster.local:5005"
              - name: ANALYSIS_URL
                value: "http://gpmt-net.default.svc.cluster.local"
              - name: APP_URL
                value: "https://gympapmt.de"
              - name: ADMIN_URL
                value: "https://admin.gympapmt.de"
              - name: NODE_ENV
                value: "production"
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: "registry-token"


