version: "3"

services:
  gpmt-api:
    container_name: gpmt-api
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - gpmt-default
    volumes:
      - ./coverage:/app/coverage
    environment:
      - STORAGE_CONNECTION_URL="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;"
      - MONGO_URL=mongodb://localhost:27017/gpmt
      - SPEECH_TOKEN=e1ba29dd157443d5a95f572562cbe2e0
      - SPEECH_REGION=westeurope
      - APP_URL=http://localhost:5000
      - ADMIN_URL=http://localhost:4000
      - NET_URL=http://gpmt-net:8088/
      - NODE_ENV=testing
      - AUTH_SIGN_SECRET=abc
      - HASH_SALT_ROUNDS=10
      - PORT=8089
      - RASA_URL=http://rasa:5005/
      - ADMIN_PASSWORD=password
    ports:
      - "8089:8089"
    
  gpmt-mongo:
    image: mongo
    volumes:
      - gpmt-mongo-volume:/data/db
    networks:
      - gpmt-default
    ports:
      - "27017:27017"

  gpmt-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose
    volumes:
      - gpmt-storage-volume:/data    
    networks:
      - gpmt-default
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

volumes:
  gpmt-mongo-volume:
  gpmt-storage-volume:

networks:
  gpmt-default:
    name: gpmt-default