apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpmt-api-chat
    namespace: api
spec:
    selector:
        matchLabels:
            app: gpmt-api-chat
    template:
        metadata:
            labels:
                app: gpmt-api-chat
        spec:
            containers:
            - name: gpmt-api-chat
              image: gpmtregistry.azurecr.io/gpmt-api-chat:v1
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: registry-token
