apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpmt-api
    namespace: "default"
spec:
    selector:
        matchLabels:
            app: gpmt-api
    template:
        metadata:
            labels:
                app: gpmt-api
        spec:
            containers:
            - name: gpmt-api
              # image: gpmtregistry.azurecr.io/gpmt-api:v1
              image: hakrac/gpmt-api:latest
              imagePullPolicy: Always
              env:
              - name: AUTH_SIGN_SECRET 
                value: "abc"
              - name: HASH_SALT_ROUNDS
                value: "10"
              - name: PORT
                value: "80"
              - name: MONGO_URL
                value: "gpmt-mongodb.default.svc.cluster.local"
              - name: RASA_URL
                value: "http://rasa-x-rasa-production.rasa.svc.cluster.local:5005"
              - name: REDIS_URL
                value: "redis://gpmt-redis.default.svc.cluster.local"
              ports:
              - containerPort: 80
              volumeMounts:
              - name: "gpmt-photo"
                mountPath: /data/gpmt-photo
              # imagePullSecrets:
              # - name: registry-token
            volumes:
            - name: gpmt-photo
              persistentVolumeClaim:
                claimName: gpmt-photo-pvc
            
