apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpmt-api
    namespace: "default"
spec:
    selector:
        matchLabels:
            app: gpmt-api
    template:
        metadata:
            labels:
                app: gpmt-api
        spec:
            containers:
            - name: gpmt-api
              image: gpmtcontainerregistry.azurecr.io/gpmt-api
              imagePullPolicy: Always
              env:
              - name: AUTH_SIGN_SECRET 
                value: "abc"
              - name: HASH_SALT_ROUNDS
                value: "10"
              - name: PORT
                value: "80"
              - name: MONGO_URL
                value: "mongodb://gpmtdb:aD3OP3ay1EXrS8NfT5Qs5kyZlb9FXMK9jcMfaefv48h84pT9RHrQjoFgSTnu9Fh8niMUNTysETPQTbzQThUADg%3D%3D@gpmtdb.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@gpmtdb@"
              - name: RASA_URL
                value: "http://rasa-x-rasa-production.rasa.svc.cluster.local:5005"
              - name: REDIS_URL
                value: "redis://gpmt-redis.default.svc.cluster.local"
              - name: ANALYSIS_URL
                value: "http://gpmt-net.default.svc.cluster.local"
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: "registry-token"