apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: gpmt-api-ingress
    namespace: api
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
    - http:
        paths:
        - path: /data
          pathType: Prefix
          backend:
            serviceName: gpmt-api-data
            servicePort: 80

        - path: /chat
          pathType: Prefix
          backend:
            serviceName: gpmt-api-chat
            servicePort: 80
        
        - path: /auth
          pathType: Prefix
          backend:
            serviceName: gpmt-api-auth
            servicePort: 80
        
