controller:
    replicaCount: 1
    service:
        loadBalancerIP: "20.101.118.68"
        annotations:
            service.beta.kubernetes.io/azure-dns-label-name: "api-gpmt"

    nodeSelector:
        beta.kubernetes.io/os: linux
    
    admissionWebhooks:
        patch:
            nodeSelector:
                beta.kubernetes.io/os: linux

defaultBackend:
    nodeSelector:
        beta.kubernetes.io/os: linux

