apiVersion: v1
kind: Service
metadata:
    name: gpmt-api-chat
    namespace: "default"
spec:
    type: ClusterIP
    ports:
    - port: 80
    selector:
        app: gpmt-api-chat
---
apiVersion: v1
kind: Service
metadata:
    name: gpmt-api-data
    namespace: "default"
spec:
    type: ClusterIP
    ports:
    - port: 80    
    selector:
        app: gpmt-api-data
---
apiVersion: v1
kind: Service
metadata:
    name: gpmt-api-auth
    namespace: "default"
spec:
    type: ClusterIP
    ports:
    - port: 80
    selector:
        app: gpmt-api-auth
---
apiVersion: v1
kind: Service
metadata:
    name: gpmt-mongodb
    labels:
        app: gpmt-mongodb
spec:
    clusterIP: None
    ports:
    - port: 27017
      name: mongodb
    selector:
        app: gpmt-mongodb


