on: [release]

name: Deployment to Azure Kubernetes Service

env:
    CLUSTER_NAME: GPMTCluster
    RESOURCE_GROUP: GPMTResourceGroup
    REGISTRY_SECRET_NAME: registry-token
    
jobs:
    test:
      name: Testing
      runs-on: ubuntu-latest
      env:
        STORAGE_CONNECTION_URL: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;"
        MONGO_URL: "mongodb://localhost:27017/gpmt"
        SPEECH_TOKEN: "e1ba29dd157443d5a95f572562cbe2e0"
        SPEECH_REGION: "westeurope"
        APP_URL: "http://localhost:5000"
        ADMIN_URL: "http://localhost:4000"
        NET_URL: "http://gpmt-net:8088/"
        NODE_ENV: "testing"
        AUTH_SIGN_SECRET: "abc"
        HASH_SALT_ROUNDS: "10"
        PORT: "8089"
        RASA_URL: "http://localhost:5005/"
        ADMIN_PASSWORD: "password"
      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      
      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install
      
      - name: Start database and blob service
        run: bash ./install.sh

      - name: Run tests
        run: npm run test
      
    build:
      name: Build and push container to ACR
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@v2
      
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build container
        run: |
          docker build ./ \
          -t ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-api:${{ github.event.release.tag_name }} \
          --build-arg API_VERSION=${{ github.event.release.tag_name }}
      
      - name: Push container
        run: |
          docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-api:${{ github.event.release.tag_name }}
     
    deploy:
      name: Deploy to AKS
      needs: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2 
      
      - name: Set AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      
      - name: Create k8s registry secret
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.REGISTRY_USERNAME }}.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: ${{ env.REGISTRY_SECRET_NAME }}
          namespace: "default"

      - name: Create k8s cosmos secret
        uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=url=${{ secrets.COSMOS_URL }}
          secret-name: cosmosdb
          namespace: "default"

      - name: Create k8s azure storage secret
        uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=url=${{ secrets.STORAGE_CONNECTION_URL }}
          secret-name: azure-storage
          namespace: "default"

      - name: Create k8s admin password secret
        uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=password=${{ secrets.ADMIN_PASSWORD }}
          secret-name: admin
          namespace: "default"
      
      - name: Create k8s speech secret
        uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=token=${{ secrets.SPEECH_TOKEN }} --from-literal=region=${{ secrets.SPEECH_REGION }}
          secret-name: speech
          namespace: "default"

      - uses: azure/setup-helm@v1
        with:
          version: '3.5.3'
          id: install

      - name: Fetch helm repositories
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
  
      - name: Deploy nginx ingress controller
        run: |
          helm template nginx-ingress ingress-nginx/ingress-nginx \
          --values ./manifest/nginx.values.yaml \
          --namespace "default" | kubectl apply -n default -f -
      
      - name: Deploy certificate manager
        run: |
          helm upgrade --install cert-manager jetstack/cert-manager \
          --values ./manifest/cert-manager.values.yaml \
          --set installCRDs=true \
          --namespace cert-manager --create-namespace 
      
      - name: Deploy api service
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
              manifest/deployments.yaml
              manifest/services.yaml
              manifest/issuer.yaml
          imagepullsecrets: |
              ${{ env.REGISTRY_SECRET_NAME }}
          images: |
            ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-api:${{ github.event.release.tag_name }}
          namespace: "default"

      - name: Deploy api ingress
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
              manifest/ingress.yaml
          namespace: "default"
